"""add price to seats

Revision ID: 961d2c1ba37d
Revises: 3dfad97d3e42
Create Date: 2026-10-03 21:12:44.243377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '961d2c1ba37d'
down_revision: Union[str, Sequence[str], None] = '3dfad97d3e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seats', sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seats', 'price')
    # ### end Alembic commands ###
